services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: sakibsakib/mrsohofrontend:latest
    platform: linux/amd64
    environment:
      NODE_ENV: development
    env_file:
      - .env
    ports:
      - "3001:3001"